# Generated by Django 5.2.12 on 2026-03-11 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eBusinessApp', '0005_jobapplication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
